//! Diesel SQL function definitions for the `pgmq` extension.

use crate::types::QueueMetrics;
use diesel::deserialize::{FromSql, FromSqlRow};
use diesel::dsl::sql;
use diesel::expression::SqlLiteral;
use diesel::pg::{Pg, PgValue};
use diesel::prelude::*;
use diesel::query_builder::SelectClauseExpression;
use diesel::row::Row;
use diesel::sql_types::{Array, BigInt, Integer, Jsonb, Nullable, Record, Text, Timestamptz};

/// Diesel SQL type that can be used as the return type of diesel SQL functions generated by
/// the [`declare_sql_function`] macro.
// Relevant example: https://github.com/diesel-rs/diesel/blob/main/examples/postgres/composite_types/examples/composite2rust_colors.rs
type PgMessage = diesel::sql_types::Record<(
    // msg_id
    BigInt,
    // read_ct
    Integer,
    // enqueued_at
    Timestamptz,
    // last_read_at
    Nullable<Timestamptz>,
    // vt
    Timestamptz,
    // message
    Jsonb,
    // headers
    Nullable<Jsonb>,
)>;

impl<T, H> FromSql<PgMessage, Pg> for crate::Message<T, H>
where
    T: for<'de> serde::Deserialize<'de>,
    H: for<'de> serde::Deserialize<'de>,
{
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (msg_id, read_ct, enqueued_at, last_read_at, vt, message, headers): (
            _,
            _,
            _,
            _,
            _,
            serde_json::Value,
            Option<serde_json::Value>,
        ) = FromSql::<PgMessage, Pg>::from_sql(bytes)?;

        let headers = if let Some(headers) = headers {
            Some(H::deserialize(headers)?)
        } else {
            None
        };

        Ok(Self {
            msg_id,
            read_ct,
            enqueued_at,
            last_read_at,
            vt,
            message: T::deserialize(message)?,
            headers,
        })
    }
}

type PgListTopicBindingsRow = diesel::sql_types::Record<(
    // pattern
    Text,
    // queue_name
    Text,
    // bound_at
    Timestamptz,
    // compiled_regex
    Text,
)>;

impl FromSql<PgListTopicBindingsRow, Pg> for crate::types::ListTopicBindingsRow {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (pattern, queue_name, bound_at, compiled_regex) =
            FromSql::<PgListTopicBindingsRow, Pg>::from_sql(bytes)?;

        Ok(Self {
            pattern,
            queue_name,
            bound_at,
            compiled_regex,
        })
    }
}

type PgSendBatchTopicRow = diesel::sql_types::Record<(
    // queue_name
    Text,
    // msg_id
    BigInt,
)>;

impl FromSql<PgSendBatchTopicRow, Pg> for crate::types::SendBatchTopicRow {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (queue_name, msg_id) = FromSql::<PgSendBatchTopicRow, Pg>::from_sql(bytes)?;

        Ok(Self { queue_name, msg_id })
    }
}

type PgListNotifyInsertThrottlesRow = diesel::sql_types::Record<(
    // queue_name
    Text,
    // throttle_interval_ms
    Integer,
    // last_notified_at
    Timestamptz,
)>;

impl FromSql<PgListNotifyInsertThrottlesRow, Pg> for crate::types::ListNotifyInsertThrottlesRow {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (queue_name, throttle_interval_ms, last_notified_at) =
            FromSql::<PgListNotifyInsertThrottlesRow, Pg>::from_sql(bytes)?;

        Ok(Self {
            queue_name,
            throttle_interval_ms,
            last_notified_at,
        })
    }
}

/// Tuple representing the Rust types corresponding to the `pgmq.meta` table columns
type PGMQueueMetaTuple = (String, bool, bool, chrono::DateTime<chrono::Utc>);

impl From<PGMQueueMetaTuple> for crate::types::PGMQueueMeta {
    fn from((queue_name, is_partitioned, is_unlogged, created_at): PGMQueueMetaTuple) -> Self {
        Self {
            queue_name,
            is_partitioned,
            is_unlogged,
            created_at,
        }
    }
}

// Because we defined a diesel schema for the `pgmq.meta` table, we can use the `SqlType` instead
// of manually defining the tuple type like we do for the other SQL function return types.
type PgPGMQueueMeta = diesel::sql_types::Record<crate::queue::diesel::schema::meta::SqlType>;

impl FromSql<PgPGMQueueMeta, Pg> for crate::types::PGMQueueMeta {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let value: PGMQueueMetaTuple = FromSql::<PgPGMQueueMeta, Pg>::from_sql(bytes)?;
        Ok(value.into())
    }
}

/*
The `FromSqlRow` derive adds a `Queryable` implementation that conflicts with the implementation
added by the `HasQuery` derive, which we need in order to use `PGMQueueMeta` in direct SQL queries.
However, we also need `PGMQueueMeta` to implement `FromSqlRow` in order to use `PGMQueueMeta` as
the return type of the `pgmq.list_queues` SQL function, so we implement it manually here.
 */
impl FromSqlRow<PgPGMQueueMeta, Pg> for crate::types::PGMQueueMeta {
    fn build_from_row<'a>(row: &impl Row<'a, Pg>) -> diesel::deserialize::Result<Self> {
        let value: PGMQueueMetaTuple = FromSqlRow::<PgPGMQueueMeta, Pg>::build_from_row(row)?;
        Ok(value.into())
    }
}

type PgQueueMetricsTuple = (
    // queue_name
    Text,
    // queue_length
    BigInt,
    // newest_msg_age_sec
    Nullable<Integer>,
    // oldest_msg_age_sec
    Nullable<Integer>,
    // total_messages
    BigInt,
    // scrape_time
    Timestamptz,
    // queue_visible_length
    BigInt,
    // default_partition_length
    Nullable<BigInt>,
);
type PgQueueMetrics = diesel::sql_types::Record<PgQueueMetricsTuple>;

impl FromSql<PgQueueMetrics, Pg> for crate::types::QueueMetrics {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (
            queue_name,
            queue_length,
            newest_msg_age_sec,
            oldest_msg_age_sec,
            total_messages,
            scrape_time,
            queue_visible_length,
            default_partition_length,
        ) = FromSql::<PgQueueMetrics, Pg>::from_sql(bytes)?;

        Ok(Self {
            queue_name,
            queue_length,
            newest_msg_age_sec,
            oldest_msg_age_sec,
            total_messages,
            scrape_time,
            queue_visible_length,
            default_partition_length,
        })
    }
}

impl QuerySource for pgmq_metrics_all {
    type FromClause = Self;
    type DefaultSelection = SqlLiteral<Record<PgQueueMetricsTuple>>;

    fn from_clause(&self) -> Self::FromClause {
        *self
    }

    fn default_selection(&self) -> Self::DefaultSelection {
        // Todo: Does using `sql` here cause the query to not use the prepared statement cache?
        // Todo: Use a string constant shared with sqlx/rust-postgres for the list of fields?
        // Todo: Implement `Table` for `QueueMetrics` even though we don't have an actual DB table related to it?
        //  This would allow statically generating the field selection list as well as a tuple to use in place of `PgQueueMetricsTuple`

        // As long as the order of these fields matches the order of the `PgQueueMetricsTuple`, the
        // order of the fields in the SQL type can be changed without breaking anything
        sql("(queue_name, queue_length, newest_msg_age_sec, oldest_msg_age_sec, total_messages, scrape_time, queue_visible_length, default_partition_length, bar)")
    }
}

#[declare_sql_function]
extern "SQL" {
    #[sql_name = "pgmq.create"]
    fn pgmq_create(queue_name: Text);

    #[sql_name = "pgmq.create_unlogged"]
    fn pgmq_create_unlogged(queue_name: Text);

    #[sql_name = "pgmq.create_partitioned"]
    fn pgmq_create_partitioned(
        queue_name: Text,
        partition_interval: Text,
        retention_interval: Text,
    );

    #[sql_name = "pgmq.convert_archive_partitioned"]
    fn pgmq_convert_archive_partitioned(
        table_name: Text,
        partition_interval: Text,
        retention_interval: Text,
    );

    #[sql_name = "pgmq.send"]
    fn pgmq_send(queue_name: Text, msg: Jsonb, headers: Jsonb, delay: Integer) -> BigInt;

    #[sql_name = "pgmq.send_batch"]
    fn pgmq_send_batch(
        queue_name: Text,
        msgs: Array<Jsonb>,
        headers: Nullable<Array<Jsonb>>,
        delay: Integer,
    ) -> BigInt;

    #[sql_name = "pgmq.read"]
    fn pgmq_read(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.pop"]
    fn pgmq_pop(queue_name: Text, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.archive"]
    fn pgmq_archive(queue_name: Text, msg_ids: Array<BigInt>) -> BigInt;

    #[sql_name = "pgmq.delete"]
    fn pgmq_delete(queue_name: Text, msg_ids: Array<BigInt>) -> BigInt;

    #[sql_name = "pgmq.set_vt"]
    fn pgmq_set_vt(queue_name: Text, msg_ids: Array<BigInt>, vt: Integer) -> PgMessage;

    #[sql_name = "pgmq.create_fifo_index"]
    fn pgmq_create_fifo_index(queue_name: Text);

    #[sql_name = "pgmq.create_fifo_indexes_all"]
    fn pgmq_create_fifo_indexes_all();

    #[sql_name = "pgmq.read_grouped"]
    fn pgmq_read_grouped(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_head"]
    fn pgmq_read_grouped_head(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_rr"]
    fn pgmq_read_grouped_rr(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.bind_topic"]
    fn pgmq_bind_topic(pattern: Text, queue_name: Text);

    #[sql_name = "pgmq.unbind_topic"]
    fn pgmq_unbind_topic(pattern: Text, queue_name: Text);

    #[sql_name = "pgmq.list_topic_bindings"]
    fn pgmq_list_topic_bindings(queue_name: Text) -> PgListTopicBindingsRow;

    #[sql_name = "pgmq.list_topic_bindings"]
    fn pgmq_list_topic_bindings_all() -> PgListTopicBindingsRow;

    #[sql_name = "pgmq.send_topic"]
    fn pgmq_send_topic(routing_key: Text, msg: Jsonb, headers: Jsonb, delay: Integer) -> Integer;

    #[sql_name = "pgmq.send_batch_topic"]
    fn pgmq_send_batch_topic(
        routing_key: Text,
        msgs: Array<Jsonb>,
        headers: Nullable<Array<Jsonb>>,
        delay: Integer,
    ) -> PgSendBatchTopicRow;

    #[sql_name = "pgmq.enable_notify_insert"]
    fn pgmq_enable_notify_insert(queue_name: Text, throttle_interval_ms: Integer);

    #[sql_name = "pgmq.update_notify_insert"]
    fn pgmq_update_notify_insert(queue_name: Text, throttle_interval_ms: Integer);

    #[sql_name = "pgmq.disable_notify_insert"]
    fn pgmq_disable_notify_insert(queue_name: Text);

    #[sql_name = "pgmq.list_notify_insert_throttles"]
    fn pgmq_list_notify_insert_throttles() -> PgListNotifyInsertThrottlesRow;

    #[sql_name = "pgmq.list_queues"]
    fn pgmq_list_queues() -> PgPGMQueueMeta;

    #[sql_name = "pgmq.acquire_queue_lock"]
    fn pgmq_acquire_queue_lock(queue_name: Text);

    #[sql_name = "pgmq.purge_queue"]
    fn pgmq_purge_queue(queue_name: Text) -> BigInt;

    #[sql_name = "pgmq.drop_queue"]
    fn pgmq_drop_queue(queue_name: Text);

    #[sql_name = "pgmq.metrics"]
    fn pgmq_metrics(queue_name: Text) -> PgQueueMetrics;

    #[sql_name = "pgmq.metrics_all"]
    fn pgmq_metrics_all() -> PgQueueMetrics;

    #[sql_name = "pgmq.read_with_poll"]
    fn pgmq_read_with_poll(
        queue_name: Text,
        vt: Integer,
        qty: Integer,
        max_poll_seconds: Integer,
        poll_interval_ms: Integer,
    ) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_with_poll"]
    fn pgmq_read_grouped_with_poll(
        queue_name: Text,
        vt: Integer,
        qty: Integer,
        max_poll_seconds: Integer,
        poll_interval_ms: Integer,
    ) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_rr_with_poll"]
    fn pgmq_read_grouped_rr_with_poll(
        queue_name: Text,
        vt: Integer,
        qty: Integer,
        max_poll_seconds: Integer,
        poll_interval_ms: Integer,
    ) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_head_with_poll"]
    fn pgmq_read_grouped_head_with_poll(
        queue_name: Text,
        vt: Integer,
        qty: Integer,
        max_poll_seconds: Integer,
        poll_interval_ms: Integer,
    ) -> PgMessage;
}
